spring.application.name=Harbr

spring.datasource.url=jdbc:postgresql://localhost:5432/harbr
spring.datasource.username=harbr
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.hibernate.packages-to-scan=com.harbr.*.domain

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

harbr.jwt.secretKey=Y2hhbmdlLXRoaXMtdG8tYS1sb25nLXNlY3VyZS1rZXktaW4tcHJvZHVjdGlvbi1lbnZpcm9ubWVudA==
harbr.jwt.accessTokenExpiration=900000
harbr.jwt.refreshTokenExpiration=604800000

harbr.payment.provider=mock
harbr.storage.local.base-path=./uploads

harbr.search.elasticsearch.enabled=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.harbr
springdoc.default-produces-media-type=application/json

logging.level.org.hibernate.SQL=debug