spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    clean-disabled: true

harbr:
  jwt:
    secret-key: ${HARBR_JWT_SECRET_KEY}
  payment:
    provider: ${HARBR_PAYMENT_PROVIDER:stripe}
    stripe-secret-key: ${STRIPE_SECRET_KEY}
    stripe-webhook-secret: ${STRIPE_WEBHOOK_SECRET}

logging:
  level:
    root: WARN
    com.harbr: INFO
    org.hibernate.SQL: WARN