spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/harbr
    username: harbr
    password: secret
    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: harbr
    password: secret

  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    com.harbr: DEBUG
    org.hibernate.SQL: DEBUG